### ISSUE TITLE
NPE when switching to Text compare 

### ISSUE THREAD

**Issue by etraisnel2** [eclipse/org.eclipse.emf.diffmerge.core#274]
Found on Capella 

Create 2 Capella projects
Compare the 2 .aird file using "Compare with / each other"
in the left hand corner of the diffmerge editor, click the drop down menu and select "Text Compare"

`java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.diffmerge.ui.viewers.EMFDiffNode.getEditorInput()" because "input" is null
    at org.eclipse.emf.diffmerge.ui.viewers.ComparisonViewer.inputChanged(ComparisonViewer.java:2376)
    at org.eclipse.emf.diffmerge.ui.viewers.AbstractComparisonViewer.setInput(AbstractComparisonViewer.java:795)
    at org.eclipse.emf.diffmerge.connector.core.ext.TeamComparisonViewer.setInput(TeamComparisonViewer.java:516)
    at org.eclipse.compare.CompareViewerSwitchingPane.setViewer(CompareViewerSwitchingPane.java:133)
    at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:265)`
    
    
    It looks like a lack of robustness,
    Adding a guard that checks if input is not null is enough to do the trick

**Comment by etraisnel2** [comment]
Looks like it also happens when using Binary Compare
